able to make any request, e.g. from any slice
WMT-GmbH/pn532 pull request #18
Opened 2024-03-08 20:21 UTC by bool-rus

In some cases, we cannot know the size of the data being transferred at compile time, so we need to be able to send arbitrary data. The application can also reuse the data buffer.
To achieve these goals, library users can implement the BorrowRequest trait

2024-03-11 11:28 UTC, dimpolo requested changes
Hi, thanks for the suggestion!
I think it's a good addition. I've requested some changes and I'd like to ask you to transition the other Pn532 methods as well (like `process`, `process_no_response`, etc.)

2024-03-11 11:28 UTC, dimpolo commented on src/requests.rs
> +pub struct BorrowedRequest<'a> {
```suggestion
/// Pn532 Request consisting of a [`Command`] and a reference to extra command data
pub struct BorrowedRequest<'a> {
```

2024-03-11 11:28 UTC, dimpolo commented on src/protocol.rs
> +    pub fn send(&mut self, request: &impl BorrowRequest) -> Result<(), Error<I::Error>> {
```suggestion
    pub fn send<'a>(&mut self, request: impl Into<BorrowedRequest<'a>>) -> Result<(), Error<I::Error>> {
```

2024-03-11 11:28 UTC, dimpolo commented on src/requests.rs
> +}
```suggestion
impl<'a, const N: usize> From<&'a Request<N>> for BorrowedRequest<'a> {
    fn from(value: &'a Request<N>) -> BorrowedRequest<'a> {
        BorrowedRequest {
            command: value.command,
            data: &value.data,
        }
    }
}
```

2024-03-11 11:28 UTC, dimpolo commented on src/requests.rs
> +    pub fn new(command: Command, data: &'a [u8]) -> Self {
```suggestion
    #[inline]
    pub const fn new(command: Command, data: &'a [u8]) -> Self {
```

2024-03-12 05:03 UTC, bool-rus commented
done

2024-03-12 09:09 UTC, dimpolo commented
Thank you!

2024-03-12 09:09 UTC, merged